SELECT * FROM FUNCIONARIOS
SELECT * FROM DEPENDENTES
SELECT * FROM TIPOS_DEPENDENTES
-- Join sem o uso explicito do INNER JOIN
SELECT *
  FROM FUNCIONARIOS F,
       DEPENDENTES D
WHERE F.CODIGO = D.ID_FUNCIONARIO
   AND D.NOME = 'MARILUCIA'

-- Join com INNER JOIN     
SELECT F.CODIGO,
       F.NOME,
       D.CODIGO AS CODIGO_DEP,
       D.NOME AS NOME_DEP
  FROM FUNCIONARIOS AS F
LEFT JOIN DEPENDENTES AS D WITH (INDEX (idx_NOME))
   ON D.ID_FUNCIONARIO = F.CODIGO
WHERE D.NOME = 'MARILUCIA'
   
-- Cria um indice na tabela DEPENDETNES no campo NOME
CREATE INDEX idx_NOME 
   ON DEPENDENTES (NOME)
   
CREATE UNIQUE INDEX idx_pk_codigo
   ON DEPENDENTES (CODIGO)
   
-- Consultar o plano de execução