USE RA950088
GO

SELECT * FROM USUARIOS

INSERT INTO USUARIOS 
  VALUES (1, 'ADALBERTO')

INSERT INTO USUARIOS 
  VALUES (2, 'MARTA')

DELETE FROM USUARIOS WHERE CODIGO = 2

SELECT * FROM HIST_USUARIOS

CREATE TABLE USUARIOS
(CODIGO INT, 
 NOME VARCHAR(200) NOT NULL,
 PRIMARY KEY (CODIGO)
)

CREATE TABLE HIST_USUARIOS
(CODIGO INT, 
 DATA DATETIME NOT NULL,
 NOME VARCHAR(200) NOT NULL,
 TIPO_ALTERACAO VARCHAR(1) NOT NULL
 PRIMARY KEY (CODIGO,DATA)
)

CREATE TRIGGER TRG_USUARIOS_INS
ON USUARIOS
FOR INSERT
AS
BEGIN
 
  DECLARE @CODIGO INT
  DECLARE @NOME VARCHAR(200)

  SELECT @CODIGO = CODIGO,
         @NOME = NOME
    FROM INSERTED

   INSERT INTO HIST_USUARIOS
      VALUES (@CODIGO, SYSDATETIME(), @NOME, 'I')

END

CREATE TRIGGER TRG_USUARIOS_UPD_DEL
ON USUARIOS
FOR UPDATE, DELETE
AS
BEGIN
 
  DECLARE @CODIGO INT
  DECLARE @NOME VARCHAR(200)

  SELECT @CODIGO = CODIGO,
         @NOME = NOME
    FROM DELETED

   INSERT INTO HIST_USUARIOS
      VALUES (@CODIGO, SYSDATETIME(), @NOME, 'D')

END