USE RA2017208552
DROP TABLE FUNCIONARIOS

-- Cria tabela com constraings not null e pk
CREATE TABLE FUNCIONARIOS
(CODIGO INT, 
 NOME VARCHAR(200) NOT NULL,
 PRIMARY KEY (CODIGO)
)

-- Insere dados na tabela funcionaros
INSERT INTO FUNCIONARIOS (CODIGO, NOME) 
   VALUES ('1','ADALBERTO'),
          ('2','MARCOS')

CREATE TABLE TIPOS_DEPENDENTES
(CODIGO INT, 
 NOME VARCHAR(200) NOT NULL,
 PRIMARY KEY (CODIGO)
)

INSERT INTO TIPOS_DEPENDENTES (CODIGO, NOME) 
   VALUES ('1','COMPANHEIR(OA)'),
          ('2','FILH(OA)'),
          ('3','ALIMENTAND(OA)')

SELECT * FROM TIPOS_DEPENDENTES

-- Apaga registro
DELETE FROM TIPOS_DEPENDENTES 
   WHERE CODIGO = 1

-- Atualiza registro
UPDATE TIPOS_DEPENDENTES
   SET NOME = 'ALIMENTAND(OA)s'
 WHERE CODIGO = 3
 
-- Cria tabela com constraings not null, pk e fk
CREATE TABLE DEPENDENTES
(CODIGO INT,
 ID_FUNCIONARIO INT,
 TP_DEPENDENTE INT,
 NOME VARCHAR(200) NOT NULL,
 PRIMARY KEY (CODIGO),
 FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (CODIGO),
 FOREIGN KEY (TP_DEPENDENTE) REFERENCES TIPOS_DEPENDENTES (CODIGO)
)

--ALTER TABLE Pedidos ADD FOREIGN KEY (PessoaID) REFERENCES Pessoas(PessoaID);
--ALTER TABLE Pedidos DROP CONSTRAINT FK_PersonOrder;

INSERT INTO DEPENDENTES (CODIGO, ID_FUNCIONARIO, TP_DEPENDENTE, NOME) 
   VALUES (1,1,1,'MARILUCIA')

INSERT INTO DEPENDENTES (CODIGO, ID_FUNCIONARIO, TP_DEPENDENTE, NOME) 
   VALUES (2,2,2,'TEREZA')

-- Inicio Join entre tabelas
SELECT F.CODIGO,
       F.NOME,
       D.CODIGO AS COD_DEPENDENTE,
       D.NOME AS NOME_DEPENDENTE
  FROM FUNCIONARIOS AS F
INNER JOIN DEPENDENTES AS D
   ON D.ID_FUNCIONARIO = F.CODIGO