USE RA950088

CREATE TABLE MOEDAS
(CODIGO VARCHAR(10), 
 NOME VARCHAR(200) NOT NULL,
 PRIMARY KEY (CODIGO)
)

INSERT INTO MOEDAS 
  VALUES ('BTC','BITCOIN'),
         ('ETH','ETHERIUM'),
         ('BRL','BRAZILIAN REAL'),
         ('USD','AMERICAN DOLAR')
         
CREATE TABLE COTACAO_MOEDA
(CODIGO VARCHAR(10), 
 VALOR FLOAT NOT NULL,
 PRIMARY KEY (CODIGO)
)

INSERT INTO COTACAO_MOEDA 
  VALUES ('BTC',150000),
         ('ETH',2000),
         ('BRL',1),
         ('USD',5.5)

-- CRIA UMA FUNCAO
CREATE FUNCTION COTACAO (@CODIGO VARCHAR(10))
RETURNS FLOAT
AS
BEGIN
   DECLARE @VALOR FLOAT
   
   SELECT @VALOR = VALOR
     FROM COTACAO_MOEDA
    WHERE CODIGO = @CODIGO
   
   RETURN @VALOR
   
END

-- Chama uma função
SELECT CODIGO,
       dbo.COTACAO(CODIGO) AS COTACAO_MOEDA
  FROM MOEDAS
WHERE  dbo.COTACAO(CODIGO) < 10000
  
SELECT dbo.COTACAO('BTC')

-- CRIA UMA FUNCAO
CREATE FUNCTION MOEDAS_DATETIME ()
RETURNS @moedas_dt TABLE
(
CODIGO VARCHAR(10), 
NOME VARCHAR(200),
VALOR FLOAT,
DATAHOJE DATETIME
)
AS
BEGIN
   INSERT @moedas_dt
   SELECT CODIGO,
          NOME,
          dbo.COTACAO(CODIGO),
          SYSDATETIME()
     FROM MOEDAS
   
   RETURN
END

SELECT *
  FROM dbo.MOEDAS_DATETIME()