USE RA2017208552
GO

-- Cria visao
CREATE VIEW FUNCIONARIOS_DEPENDENTES AS
SELECT F.CODIGO,
    F.NOME AS NOME_FUNCIONARIO,
    D.CODIGO AS CODIGO_DEP,
    D.NOME AS NOME_DEP,
    T.NOME AS NOME_DEPENDENTE
  FROM FUNCIONARIOS AS F
  INNER JOIN DEPENDENTES AS D
  ON D.ID_FUNCIONARIO = F.CODIGO
  INNER JOIN TIPOS_DEPENDENTES AS T
  ON D.TIPOS_DEPENDENTES = T.CODIGO
GO

-- Selecionando dados da visao
SELECT *
  FROM FUNCIONARIOS_DEPENDENTES


-- Criando uma sequencia
CREATE SEQUENCE TestSequence
AS BIGINT
START WITH 1
INCREMENT BY 1;

-- Obtendo proximo valor da sequencia
SELECT NEXT VALUE
  FOR TestSequence