SELECT * FROM FUNCIONARIOS
SELECT * FROM DEPENDENTES
SELECT * FROM TIPOS_DEPENDENTES

INSERT INTO FUNCIONARIOS (CODIGO, NOME) 
   VALUES ('3','TEO'),
          ('4','MARIANA')

-- Inicio Join entre tabelas
SELECT F.CODIGO,
       F.NOME,
       D.CODIGO AS CODIGO_DEP,
       D.NOME AS NOME_DEP,
       T.NOME
  FROM FUNCIONARIOS AS F
INNER JOIN DEPENDENTES AS D
   ON D.ID_FUNCIONARIO = F.CODIGO
INNER JOIN TIPOS_DEPENDENTES AS T
   ON D.TP_DEPENDENTE = T.CODIGO   

-- Left Join entre tabelas - traz todos os dados da tabela a esquerda
-- mesmo sem correspondencia com tabela a direita
SELECT F.CODIGO,
       F.NOME,
       D.CODIGO AS CODIGO_DEP,
       D.NOME AS NOME_DEP
  FROM FUNCIONARIOS AS F
LEFT JOIN DEPENDENTES AS D
   ON D.ID_FUNCIONARIO = F.CODIGO

-- Right Join entre tabelas - traz todos os dados da tabela a direita
-- mesmo sem correspondencia com tabela a esquerda
SELECT F.CODIGO,
       F.NOME,
       D.CODIGO AS CODIGO_DEP,
       D.NOME AS NOME_DEP,
       T.NOME
  FROM FUNCIONARIOS AS F
INNER JOIN DEPENDENTES AS D
   ON D.ID_FUNCIONARIO = F.CODIGO
RIGHT JOIN TIPOS_DEPENDENTES AS T
   ON D.TP_DEPENDENTE = T.CODIGO   

-- Full join - seleciona dados de todas as tabelas
SELECT F.CODIGO,
       F.NOME,
       D.CODIGO AS CODIGO_DEP,
       D.NOME AS NOME_DEP,
       T.NOME
  FROM FUNCIONARIOS AS F
FULL JOIN DEPENDENTES AS D
   ON D.ID_FUNCIONARIO = F.CODIGO
FULL JOIN TIPOS_DEPENDENTES AS T
   ON D.TP_DEPENDENTE = T.CODIGO